wingsuit:
  imageConfig:
    styles:
      1x1_xxs_sc:
        label: Small 1x1
        width: 80
        height: 80
      8x7_xxs_sc:
        label: XSmall 8x7
        width: 460
        height: 402
      8x7_xs_sc:
        label: Small 8x7
        width: 640
        height: 560
      16x9_xxxs_sc:
        label: XXXSmall 16x9 ()
        width: 220
        height: 124
      16x9_xxs_sc:
        label: XXSmall 16x9
        width: 460
        height: 258
      16x9_xs_sc:
        label: XSmall 16x9
        width: 640
        height: 359
      16x9_sm_sc:
        label: SM 16x9
        width: 768
        height: 432
      16x9_md_sc:
        label: LG 16x9
        width: 1024
        height: 576
      16x9_xl_sc:
        label: XL 16x9
        width: 1280
        height: 720
      16x9_xxl_sc:
        label: XXL 16x9
        width: 1900
        height: 1068
    stylesResponsive:
      card-hero:
        style: 16x9_xs_sc
        breakpoints:
          xxs: 8x7_xxs_sc
          xs: 8x7_xs_sc
      article:
        style: 16x9_xl_sc
        breakpoints:
          xxs: 8x7_xxs_sc
          xs: 8x7_xs_sc
          sm: 16x9_sm_sc
          md: 16x9_md_sc
      card-default:
        style: 16x9_xxs_sc
        breakpoints:
          xxs: 1x1_xxs_sc
          xs: 1x1_xxs_sc
          sm: 1x1_xxs_sc
      card-horizontal:
        style: 1x1_xxs_sc
        breakpoints:
          xxs: 1x1_xxs_sc
          xs: 1x1_xxs_sc
          sm: 1x1_xxs_sc
      card-horizontal-large:
        style: 16x9_xxxs_sc
        breakpoints:
          xxs: 1x1_xxs_sc
          xs: 1x1_xxs_sc
          sm: 1x1_xxs_sc

    breakpoints:
      xxs:
        mediaQuery: '(min-width: 0px) and (max-width: 459px)'
      xs:
        mediaQuery: '(min-width: 460px) and (max-width: 639px)'
      sm:
        mediaQuery: 'all and (min-width: 640px) and (max-width: 767px)'
      md:
        mediaQuery: 'all and (min-width: 768px) and (max-width: 1023px)'
      lg:
        mediaQuery: 'all and (min-width: 1024px) and (max-width: 1279px)'
      xl:
        mediaQuery: 'all and (min-width: 1280px)'
