version: 2.1

executors:
  sb_node_18_classic:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'medium+', 'large', 'xlarge']
        default: 'small'
    working_directory: /tmp/storybook
    docker:
      - image: cimg/node:18.17.1
        environment:
          NODE_OPTIONS: --max_old_space_size=6144
    resource_class: <<parameters.class>>

jobs:
  install:
    executor:
      class: small
      name: sb_node_18_classic
    steps:
      - checkout
      - restore_cache:
          name: Restore core dependencies cache
          keys:
            - core-dependencies-v5-{{ checksum "yarn.lock" }}
            - core-dependencies-v5-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Check that yarn.lock is not corrupted
          command: yarn repo-dirty-check
      - save_cache:
          name: Cache core dependencies
          key: core-dependencies-v5-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - examples
            - packages
            - .cache
  build:
    executor:
      class: large
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Bootstrap
          command: yarn bootstrap --core
      - persist_to_workspace:
          root: .
          paths:
            - packages
            - presets
            - starter-kits
            - examples
            - .cache
  packtracker:
    executor:
      class: large
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Report webpack stats for manager of official storybook
          command: |
            cd examples/official-wingsuit
            yarn packtracker
  examples:
    executor:
      class: large
      name: sb_node_18_classic
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: examples
          command: |
            yarn build-storybooks
      - persist_to_workspace:
          root: .
          paths:
            - built-storybooks
  publish:
    executor:
      class: small
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: running local registry
          command: yarn local-registry --publish
      - persist_to_workspace:
          root: .
          paths:
            - .verdaccio-cache
  init-e2e:
    docker:
      - image: cypress/included:cypress-12.8.1-node-18.14.1-chrome-111.0.5563.110-1-ff-111.0.1-edge-111.0.1661.51-1
        environment:
          TERM: xterm
    working_directory: /tmp/storybook
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: running local registry
          command: yarn local-registry --port 6000 --open
          background: true
      - run:
          name: wait for registry
          command: yarn wait-on http://localhost:6000
      - run:
          name: set registry
          command: yarn config set registry http://localhost:6000/
      - run:
          name: test local registry
          command: yarn info @wingsuit-designsystem/core
      - run:
          name: run e2e tests
          command: yarn test:e2e-framework
      - store_artifacts:
          path: /tmp/storybook/cypress
          destination: cypress
#  examples-v2-yarn-2:
#    docker:
#      - image: cypress/included:4.7.0
#        environment:
#          TERM: xterm
#    working_directory: /tmp/storybook
    # parallelism: 10
#    steps:
 #     - checkout
#      - attach_workspace:
#          at: .
#      - run:
#          name: running local registry
#          command: yarn local-registry --port 6000 --open
#          background: true
#      - run:
#          name: wait for registry
#          command: yarn wait-on http://localhost:6000
#      - run:
#          name: set registry
#          command: yarn config set registry http://localhost:6000/
#      - run:
#          name: test local registry
#          command: yarn info @wingsuit-designsystem/core
#      - run:
#          name: run e2e tests
#          command: yarn test:e2e-framework yarn2Cra
#      - store_artifacts:
#          path: /tmp/storybook/cypress
#          destination: cypress
  e2e:
    working_directory: /tmp/storybook
    docker:
      - image: cypress/included:cypress-12.8.1-node-18.14.1-chrome-111.0.5563.110-1-ff-111.0.1-edge-111.0.1661.51-1
        environment:
          TERM: xterm
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: running example
          command: yarn serve-storybooks
          background: true
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install g++ build-essential
          command: apt-get install g++ build-essential -y

      - run:
          name: install cypress
          command: yarn install
      - run:
          name: await running examples
          command: yarn await-serve-storybooks
      - run:
          name: cypress run
          command: yarn test:e2e --record --key 2311d788-c8ef-458b-b009-4cd3aee65180
  chromatic:
    executor:
      class: small
      name: sb_node_18_classic
    working_directory: /tmp/storybook
    parallelism: 4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Tailwind
          command: |
            cd starter-kits/tailwind
            npx chromatic --exit-zero-on-changes
  smoke-tests:
    executor:
      class: small
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run  (smoke test)
          command: |
            cd examples/official-wingsuit
            yarn storybook --smoke-test --quiet
      - run:
          name: Run Tailwind (smoke test)
          command: |
            cd starter-kits/tailwind
            yarn dev:storybook --smoke-test --quiet
      - run:
          name: Run Tailwind (drupal smoke test)
          command: |
            cd starter-kits/tailwind
            yarn build:drupal

      - run:
          name: Run Bootstrap (smoke test)
          command: |
            cd starter-kits/vanilla-scss
            yarn dev:storybook --smoke-test --quiet
      - run:
          name: Run Bootstrap (drupal smoke test)
          command: |
            cd starter-kits/vanilla-scss
            yarn build:drupal

  docs:
    executor:
      class: large
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            cd docs
            yarn install
      - run:
          name: Build docs
          command: |
            cd docs
            yarn build:pages
  lint:
    executor:
      class: small
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  test:
    executor:
      class: medium
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test --coverage --w2 --core
      - persist_to_workspace:
          root: .
          paths:
            - coverage
  coverage:
    executor:
      class: small
      name: sb_node_18_classic
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Upload coverage
          command: yarn coverage

workflows:
  test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - build
      - examples:
          requires:
            - build
      - e2e:
          requires:
            - examples
      - smoke-tests:
          requires:
            - build
      - packtracker:
          requires:
            - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - build
      - init-e2e:
          requires:
            - publish
#      - examples-v2-yarn-2:
#          requires:
#            - publish
  deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - docs:
          requires:
            - build
